import { Transaction } from '@/types/wallet';

export const MOCK_TRANSACTIONS: Transaction[] = [
    {
      id: "1",
      type: "receive" as const,
      amount: 0.05,
      timestamp: new Date(Date.now() - 3600000),
      address: "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
      status: "completed" as const,
    },
    {
      id: "2",
      type: "send" as const,
      amount: 0.025,
      timestamp: new Date(Date.now() - 7200000),
      address: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
      status: "completed" as const,
      networkFee: 0.00005,
    },
    {
      id: "3",
      type: "receive" as const,
      amount: 0.1,
      timestamp: new Date(Date.now() - 86400000),
      address: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
      status: "completed" as const,
    },
    // {
    //   id: "4",
    //   type: "receive" as const,
    //   amount: 0.1,
    //   timestamp: new Date(Date.now() - 86400000),
    //   address: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    //   status: "completed" as const,
    // },
    // {
    //   id: "5",
    //   type: "receive" as const,
    //   amount: 0.1,
    //   timestamp: new Date(Date.now() - 86400000),
    //   address: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    //   status: "completed" as const,
    // },
    // {
    //   id: "6",
    //   type: "receive" as const,
    //   amount: 0.1,
    //   timestamp: new Date(Date.now() - 86400000),
    //   address: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    //   status: "completed" as const,
    // },
    // {
    //   id: "7",
    //   type: "receive" as const,
    //   amount: 0.1,
    //   timestamp: new Date(Date.now() - 86400000),
    //   address: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    //   status: "completed" as const,
    // },
    // {
    //   id: "8",
    //   type: "receive" as const,
    //   amount: 0.1,
    //   timestamp: new Date(Date.now() - 86400000),
    //   address: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    //   status: "completed" as const,
    // },
    // {
    //   id: "9",
    //   type: "receive" as const,
    //   amount: 0.1,
    //   timestamp: new Date(Date.now() - 86400000),
    //   address: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    //   status: "completed" as const,
    // },
    // {
    //   id: "10",
    //   type: "receive" as const,
    //   amount: 0.1,
    //   timestamp: new Date(Date.now() - 86400000),
    //   address: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    //   status: "completed" as const,
    // },
  ];